### PR TITLE
Use FusedLocationProvider to get gps location.

### PR DESCRIPTION
**Pull request by svvashishtha**
ChangeLog: 
1. Use FusedLocationProvider Api to get GPS location. 
2. Removed unused settings parameters. 
3. Added default values to shared preferences values used to get a Settings object in MainActivity. This will prevent app crash on first launch.

### CODE REVIEW

**Comment by Lezh1k** [comment]
Is there option to allow using of standard location manager instead of fused location provider? 
@svvashishtha ^

**Comment by svvashishtha** [comment]
> Is there option to allow using of standard location manager instead of fused location provider?
> @svvashishtha ^

No. I can add it if it is required.

**Comment by Lezh1k** [comment]
Add, please. As I described - we can't use fused location provider on some of our devices. That's why we implemented own data fusion. 

Fusion location provider, as I know, does similar things (maybe more :)) 

So please, just add some option to change default GPS location manager to Fused Location Provider. 

Thank you :)

**Comment by svvashishtha** [comment]
> Add, please. As I described - we can't use fused location provider on some of our devices. That's why we implemented own data fusion.
> 
> Fusion location provider, as I know, does similar things (maybe more :))
> 
> So please, just add some option to change default GPS location manager to Fused Location Provider.
> 
> Thank you :)

Hi @Lezh1k, 
As you suggested, I've added a setting to switch between GPS and Fused location provider and added buttons in the UI to do so.

**Pull request merged**
